name: Apply namespace specs
on:
  push:
    branches:
      - main
    paths:
      - 'namespaces/*/spec.json'

jobs:
  apply-namespaces:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            namespaces
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.18'
      - run: go install github.com/temporalio/tcld/cmd/tcld@ffa81f5b74ea8c1d962ce9169f10bfb0f6d34f48
      - shell: bash
        env:
          TEMPORAL_CLOUD_API_KEY: ${{ secrets.TEMPORAL_CLOUD_API_KEY }}
          AUTO_CONFIRM: true
        run: |
          for specFilePath in $(find namespaces -name spec.json); do
            namespaceName=$(basename $(dirname "$specFilePath"))
            echo "::group:: Namespace:$namespaceName Specfile:$specFilePath"
            tcld namespace apply --namespace $namespaceName --spec-file $specFilePath --wait
            echo "::endgroup::"
          done

          
