name: Apply user specs

on:
  push:
    branches:
      - main
    paths:
      - 'users/*/spec.json'

jobs:
  apply-users:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            users
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.18'
      - run: go install github.com/temporalio/tcld/cmd/tcld@fe346a596d9e364496bd923567d73b3ec188e66f
      - shell: bash
        env:
          TEMPORAL_CLOUD_API_KEY: ${{ secrets.TEMPORAL_CLOUD_API_KEY }}
          AUTO_CONFIRM: true
        run: |
          for specFilePath in $(find users -name spec.json); do
            userEmail=$(jq -r '.email' $specFilePath)
            echo updating user with email=$userEmail with specification in file $specFilePath
            tcld user apply --user-email $userEmail --spec-file $specFilePath --wait
          done

    
