name: Apply namespace specs
on:
  push:
    branches:
      - main
    # paths:
    #   - 'namespaces/*/spec.json'

jobs:
  deploy-and-test-cp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            namespaces
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.18'
      - run: go install github.com/temporalio/tcld/cmd/tcld@5213f7e34f3fb67c7588954651a5267fdcf67ef0
      - shell: bash
        run: |
          for specFilePath in $(find namespaces -name spec.json); do
            namespaceName=$(basename $(dirname "$specFilePath"))
            echo updating $namespaceName namespace with specification in file $specFilePath
            tcld 
          done

          
